### ISSUE TITLE
boolean expression must not be null

### ISSUE THREAD

**Issue by prasant10050** [kalismeras61/flutter_lock_screen#2]
I am getting this error when i launch this app
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Failed assertion: boolean expression must not be null
_LockScreenState._fingerPrint 
_fingerPrint() {
    if (widget.fingerVerify) { <.... error hit this line
      widget.onSuccess();
    }
  }

**Comment by kalismeras61** [comment]
If you using example code  

Change this line

  bool isFingerprint;

to this line;
  bool isFingerprint = false;
