### ISSUE TITLE
no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null flutter

### ISSUE THREAD

**Issue by Kalyanb447-github** [kalismeras61/flutter_lock_screen#6]
on my phone fingerprint is not working with the plugin 
no_fragment_activity, local_auth plugin requires activity to be a FragmentActivity., null flutter

**Comment by chitgoks** [comment]
why was this closed? was it because the issue is with local_auth?
i was originally using FlutterActivity, when i switched to FlutterFragmentActivity all sorts of errors showed up and this was one of them.

Would it be possible to include a guide for this one?

**Comment by kalismeras61** [comment]
@chitgoks this issue not related to this plugin. 

If you want to use local_auth, You have to do below integration.

Android Integration 
Note that local_auth plugin requires the use of a FragmentActivity as opposed to Activity. This can be easily done by switching to use FlutterFragmentActivity as opposed to FlutterActivity in your manifest (or your own Activity class if you are extending the base class).

**Comment by chitgoks** [comment]
agree. this is always a pain. even though I switched to FlutterFragmentActivity another issue comes up. thanks for the reply.
