### ISSUE TITLE
null safety version?

### ISSUE THREAD

**Issue by chitgoks** [kalismeras61/flutter_lock_screen#8]
possible?

**Comment by kalismeras61** [comment]
it is already there.

**Comment by chitgoks** [comment]
im using 1.0.8 but the import says

it is still legacy,  and should not be imported into a null safe library

**Comment by kalismeras61** [comment]
https://pub.dev/packages/page_transition/versions/2.0.1-nullsafety.0

**Comment by chitgoks** [comment]
sorry i dont understand.
this is what i import

import 'package:flutter_lock_screen/flutter_lock_screen.dart';

and it gives out that warning message. correct me if im wrong, it's my understanding that the lib needs to be ported to support null safety in order for this message to go away?

**Comment by kalismeras61** [comment]
@chitgoks , sorry! it was my fault i have multiple packages. 
Will work for this one.

**Comment by chitgoks** [comment]
ok :D thank you very much. love the lib!

**Comment by kalismeras61** [comment]
Updated null safety
